from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import re

from jinja2 import Environment, PackageLoader, StrictUndefined

from dross_cli.schema import ApiSchema, load_catalog


GENERATED_NOTICE = "Generated by dross schema generator v1. DO NOT EDIT."


@dataclass(frozen=True)
class RenderedFile:
    path: Path
    content: str


def snake_case(name: str) -> str:
    return re.sub(r"(?<!^)(?=[A-Z])", "_", name).lower()


def cpp_namespace(namespace: str) -> str:
    return namespace.replace(".", "::")


def cpp_type(field_type: str) -> str:
    return {
        "content_id": "dross::ContentId",
        "entity_ref": "dross::EntityRef",
        "hex_pose": "dross::HexPose",
        "hit_points": "dross::HitPoints",
        "uint32": "std::uint32_t",
    }[field_type]


def render_files(project_root: Path) -> list[RenderedFile]:
    environment = Environment(
        loader=PackageLoader("dross_cli"),
        undefined=StrictUndefined,
        autoescape=False,
        keep_trailing_newline=True,
        trim_blocks=True,
        lstrip_blocks=True,
    )
    environment.filters.update(
        cpp_namespace=cpp_namespace,
        cpp_type=cpp_type,
        snake_case=snake_case,
    )
    catalog = load_catalog(project_root)
    rendered: list[RenderedFile] = []
    payload_template = environment.get_template("payload.hpp.j2")
    for schema in catalog:
        if schema.kind == "rule":
            continue
        rendered.append(
            RenderedFile(
                Path("include/dross/generated")
                / f"{snake_case(schema.name)}.hpp",
                payload_template.render(schema=schema, notice=GENERATED_NOTICE),
            )
        )

    shared = {"catalog": catalog, "notice": GENERATED_NOTICE}
    for template_name, destination in (
        ("codec.hpp.j2", "include/dross/generated/schema_codec.hpp"),
        ("registry.hpp.j2", "include/dross/generated/schema_registry.hpp"),
        ("events.hpp.j2", "include/dross/generated/domain_events.hpp"),
        ("docs.md.j2", "docs/command-event-api.md"),
        ("compile.cpp.j2", "tests/generated_schema_compile.cpp"),
        ("godot_api.hpp.j2", "include/dross/generated/godot_api.hpp"),
        ("godot_api.cpp.j2", "src/godot_api.cpp"),
    ):
        rendered.append(
            RenderedFile(
                Path(destination),
                environment.get_template(template_name).render(**shared),
            )
        )
    return sorted(rendered, key=lambda item: item.path.as_posix())


def generate_all(project_root: Path) -> None:
    output_root = project_root / "generated"
    expected = render_files(project_root)
    expected_paths = {item.path for item in expected}
    if output_root.exists():
        for path in sorted(output_root.rglob("*"), reverse=True):
            if path.is_file() and path.relative_to(output_root) not in expected_paths:
                path.unlink()
            elif path.is_dir() and not any(path.iterdir()):
                path.rmdir()
    for item in expected:
        destination = output_root / item.path
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(item.content, encoding="utf-8", newline="\n")


def generated_is_current(project_root: Path) -> tuple[bool, list[str]]:
    output_root = project_root / "generated"
    expected = render_files(project_root)
    differences: list[str] = []
    expected_paths = {item.path for item in expected}
    actual_paths = (
        {
            path.relative_to(output_root)
            for path in output_root.rglob("*")
            if path.is_file()
        }
        if output_root.exists()
        else set()
    )
    for item in expected:
        destination = output_root / item.path
        if not destination.is_file() or destination.read_text(encoding="utf-8") != item.content:
            differences.append(item.path.as_posix())
    differences.extend(
        path.as_posix() for path in sorted(actual_paths - expected_paths)
    )
    return not differences, differences
