from pathlib import Path

from dross_cli.generator import generate_all

from test_schema import write_schema


def authored_catalog(root: Path) -> None:
    write_schema(
        root,
        "commands",
        "place_entity.yaml",
        """
kind: command
namespace: dross.placement
name: PlaceEntity
version: 1
id: dross:place_entity
fields:
  - name: entity
    type: entity_ref
  - name: target
    type: hex_pose
""".lstrip(),
    )
    write_schema(
        root,
        "events",
        "entity_placed.yaml",
        """
kind: event
namespace: dross.placement
name: EntityPlaced
version: 1
id: dross:entity_placed
script_api: true
fields:
  - name: entity
    type: entity_ref
  - name: pose
    type: hex_pose
""".lstrip(),
    )
    write_schema(
        root,
        "events",
        "movement_started.yaml",
        """
kind: event
namespace: dross.movement
name: MovementStarted
version: 1
id: dross:movement_started
fields:
  - name: entity
    type: entity_ref
""".lstrip(),
    )
    write_schema(
        root,
        "rules",
        "placement_rule.yaml",
        """
kind: rule
namespace: dross.placement
name: PlacementRule
version: 1
id: dross:placement_rule
script_api: true
fields:
  - name: entity
    type: entity_ref
  - name: target
    type: hex_pose
""".lstrip(),
    )


def snapshot(root: Path) -> dict[str, bytes]:
    generated = root / "generated"
    return {
        path.relative_to(generated).as_posix(): path.read_bytes()
        for path in sorted(generated.rglob("*"))
        if path.is_file()
    }


def test_generation_is_idempotent_sorted_and_uses_lf(tmp_path: Path) -> None:
    authored_catalog(tmp_path)

    generate_all(tmp_path)
    first = snapshot(tmp_path)
    generate_all(tmp_path)

    assert snapshot(tmp_path) == first
    assert first
    assert all(b"\r" not in content for content in first.values())
    assert all(
        content.startswith(b"// Generated by dross schema generator")
        or content.startswith(b"<!-- Generated by dross schema generator")
        for content in first.values()
    )
    registry = first["include/dross/generated/schema_registry.hpp"].decode()
    assert registry.index("dross:entity_placed") < registry.index(
        "dross:place_entity"
    )
    godot_header = first["include/dross/generated/godot_api.hpp"].decode()
    assert "class DrossEntityPlacedEvent final" in godot_header
    assert "class DrossPlacementRuleQuery final" in godot_header
    assert godot_header.count("Event final") == 1
    compile_fixture = first["tests/generated_schema_compile.cpp"].decode()
    assert "PlacementRule" not in compile_fixture
    assert "domain_events.hpp" not in first


def test_generation_does_not_touch_handwritten_files(tmp_path: Path) -> None:
    authored_catalog(tmp_path)
    handwritten = tmp_path / "src" / "placement_handler.cpp"
    handwritten.parent.mkdir(parents=True)
    handwritten.write_text("handwritten\n", encoding="utf-8")

    generate_all(tmp_path)

    assert handwritten.read_text(encoding="utf-8") == "handwritten\n"
    assert (
        tmp_path / "generated" / "tests" / "generated_schema_compile.cpp"
    ).is_file()
