option(DROSS_ENABLE_ASAN "Enable AddressSanitizer for Dross targets" OFF)
option(DROSS_ENABLE_UBSAN "Enable UndefinedBehaviorSanitizer for Dross targets" OFF)
option(DROSS_ENABLE_TSAN "Enable ThreadSanitizer for Dross targets" OFF)

function(dross_enable_sanitizers target)
  if(MSVC)
    return()
  endif()

  set(sanitizers "")
  if(DROSS_ENABLE_ASAN)
    list(APPEND sanitizers address)
  endif()
  if(DROSS_ENABLE_UBSAN)
    list(APPEND sanitizers undefined)
  endif()
  if(DROSS_ENABLE_TSAN)
    if(DROSS_ENABLE_ASAN)
      message(FATAL_ERROR "TSan cannot be combined with ASan")
    endif()
    list(APPEND sanitizers thread)
  endif()

  if(sanitizers)
    list(JOIN sanitizers "," sanitizer_arg)
    target_compile_options(${target} PRIVATE "-fsanitize=${sanitizer_arg}" -fno-omit-frame-pointer)
    target_link_options(${target} PRIVATE "-fsanitize=${sanitizer_arg}")
  endif()
endfunction()
